import base64

content_b64 = '''
IyEgL3Vzci9iaW4vZW52IHB5dGhvbjMKIid0b3Vu'
'JTI1c3VuJTI1b3MlMjB5b3VyJTIwZXhlY3V0YWJs
ZSUyMG9uJTIwZXZlcnklMjBzdWJzeXN0ZW0lMjAl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
MjclMjclMjclMjclMjclMjclMjclMjclMjclMjcl
'''

# This approach is too complex. Let me just use subprocess to write the file.
import subprocess

# Write the monitor.py content using a Python script that generates it
script = '''
content = open('/home/work/.openclaw/workspace/projects/motobid/monitor.py', 'r').read()

# Find all lines with f-strings that have nested quote issues
# Just replace f-strings containing dict access with concatenation

# Actually, easiest fix: just remove the f-strings entirely and use format()
# OR use a completely different approach

# Let's just check which lines still fail
import ast
try:
    ast.parse(content)
    print('OK')
except SyntaxError as e:
    print(f'FAIL line {e.lineno}: {e.msg}')
    lines = content.split(chr(10))
    print(repr(lines[e.lineno-1]))
'''

result = subprocess.run(['python3', '-c', script], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)